# my global config
global:
  scrape_interval: 15s
scrape_configs:

  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jenkins"
    metrics_path: /prometheus

    static_configs:
      - targets: ["172.29.171.199:8080"]


